### ISSUE TITLE
Spanish Translate

### ISSUE THREAD

**Issue by migue2982** [mytigio/SDV_DwarvenExpansion#2]
Hello friend, I made a translation into Spanish in case you could include it in the mod. But it is not added to the game, I don't know why. If you could help me I would appreciate it. Many thanks for everything
[es.json](https://github.com/mytigio/SDV_DwarvenExpansion/files/14937537/es.json)

**Comment by mytigio** [comment]
I've added the translation file to the mod files, it will release with 1.3

**Comment by migue2982** [comment]
Fixed, it works perfectly for me now. Thank you so much

**Comment by mytigio** [comment]
@migue2982  fyi, a few updates have come out since your translation.  I've put english versions of those new lines into your es.json file, but if you want to update the translations I can fold them into the main file

**Comment by migue2982** [comment]
Hello! I have updated the translation. Thanks for letting me know. Greetings
[es.json](https://github.com/mytigio/SDV_DwarvenExpansion/files/15016538/es.json)
